site_name: MycilaDimmer
site_url: https://mathieu.carbou.me/MycilaDimmer/
repo_url: https://github.com/mathieucarbou/MycilaDimmer
repo_name: mathieucarbou/MycilaDimmer
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdoxy:
      projects:
        cppapi:
          src-dirs: src/
          full-doc: True
          doxy-cfg:
            PROJECT_NAME: MycilaDimmer
            RECURSIVE: YES
            EXTRACT_ALL: YES
            FILE_PATTERNS: "MycilaDimmer*.h"
            QUIET: YES

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - AC Dimming: ac-dimming.md
  - Cycle Stealing Algorithm: cycle_stealing.md
  - Dimmer Types: dimmers.md
  - Installation: installation.md
  - Configuration: configuration.md
  - API Reference: api.md
  - Examples: examples.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - Sponsors: sponsors.md
  - C++ API:
      - Annotated Classes: cppapi/annotated.md
      - Class Hierarchy: cppapi/hierarchy.md
      - All Classes: cppapi/classes.md
      - Namespaces: cppapi/namespaces.md
      - Files: cppapi/files.md
