# bundle exec jekyll serve --host=0.0.0.0

title: MycilaDimmer
description: ESP32 / Arduino Library to control TRIAC, Random SSR, Voltage Regulator with DfRobot DAC or PWM
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
