name: Publish Website
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "src/**"
      - "mkdocs.yml"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: sudo apt-get install -y doxygen
      - run: pip install mkdocs-material mkdoxy
      - run: mkdocs gh-deploy --force
